### ISSUE TITLE
unable to restart after one reboot

### ISSUE THREAD

**Issue by changemenemo** [YunoHost-Apps/mygpo_ynh#10]
**How to post a meaningful bug report**
1. *Read this whole template first.*
2. *Determine if you are on the right place:*
   - *If you were performing an action on the app from the webadmin or the CLI (install, update, backup, restore, change_url...), you are on the right place!*
   - *Otherwise, the issue may be due to mygpo itself. Refer to its documentation or repository for help.*
   - *When in doubt, post here and we will figure it out together.*
3. *Delete the italic comments as you write over them below, and remove this guide.*
--- 

### Describe the bug
after one reboot mygpo drops and don't want to start anymore.

### Context

- Hardware: *qemu vm on a fedora server with 10G of RAM allocated to this VM*
- YunoHost version: 4.1.8
- I have access to my server: *Through SSH | through the webadmin *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: The VM is linked to several iscsi devices located on another VM truenas which has several zvol allocated to this yunohost VM.
  - the first one is for the nextcloud data
  - The second one is for the yunohost backup
  - the third one is for the multimedia rep
  - I've included several binds also in the fstab for that purpose: 
```
/media/back/yunohost.backup     /home/yunohost.backup   none    defaults,bind   0   0
/media/media_share/yunohost.multimedia  /home/yunohost.multimedia       none    defaults,bind   0   0
/media/media_share/funkwhale  /home/yunohost.app/funkwhale      none    defaults,bind   0   0
/media/media_share/peertube   /home/yunohost.app/peertube       none    defaults,bind   0   0

/media/web/www  /var/www        none    defaults,bind   0       0
```
the last line is for a disk image located on the same server allocated to the VM yunohost directly on SSD.  so no iscsi device or truenas link for that one.

### Steps to reproduce
just a reboot and then the python environment doesn't seem to be accessible anymore? 

### Expected behavior
the log should be more clear about the problem since /run/mygpo.sock doesn't exist.

### Logs
[yunohost paste](
https://paste.yunohost.org/atuqerisas)

**Comment by Jules-Bertholet** [comment]
Are you using the latest version of the package?

**Comment by boistordu** [comment]
Yes no updates yet n the yunohost webmin about this app

**Comment by boistordu** [comment]
Feel free to ask me if you need any other specifics or if you want me to test a few things. 
My only guess is that the python environment is not sync properly ?
because from what I can see in htop or bpytop, gunicorn for mygpo is launched. There is a statement of this in the list of the process.

**Comment by Jules-Bertholet** [comment]
I just pushed a new update for the package, could you try installing it ?

**Comment by boistordu** [comment]
Yes, will do when my dear co-members of my independent vpn service provider have finished to do messed up things with their already messed up vpn configurations:)

**Comment by boistordu** [comment]
I have an update for galene, I don't have an update for gpo yet

**Comment by Jules-Bertholet** [comment]
@boistordu There is a delay between new pushes to `master` and getting an update notification, you can force an immediate upgrade with `yunohost app upgrade mygpo -F -u https://github.com/YunoHost-Apps/mygpo_ynh`

**Comment by boistordu** [comment]
mmmh okey that I didn't know. well it's up to date now. I just had to wait 24 hours.
the webapp is reachable again and the service has started again.
Would you like me to do a test or anything alike?

**Comment by Jules-Bertholet** [comment]
@boistordu Could you reboot, and see if the services start properly?

**Comment by boistordu** [comment]
yes it's working now apparently, even with my iscsi problems of not being able to shutdown properly. 
Any idea what was the problem?

**Comment by boistordu** [comment]
what i can see from syslog, even if it works, and since it's the only service that I see with that kind of error:
`Apr 29 20:03:54  systemd[1]: /etc/systemd/system/mygpo-beat.service:3: Failed to add dependency on mygpo.scoket, ignoring: Unknown error -22`
tell me if you want to look into it.

**Comment by Jules-Bertholet** [comment]
As long as `mygpo-beat.service` starts, it should be fine, but I'll look into it
